mongo:
  uri: "mongodb://localhost:27017"
  database: "product-service"
mysql:
  order-service:
    uri: "root:965519@tcp(localhost:3306)/order-service"
  inventory-service:
    uri: "root:password@tcp(localhost:3306)/inventory-service"
server:
  port: 8080
